using Microsoft.AspNetCore.Identity;

namespace API.Entities
{
    //This entity could be also automatically generated by Identity.
    public class UserRole: IdentityUserRole<int>
    {
        public User User { get; set; }
        public Role Role { get; set; }
    }
}